//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualWorkFriendBot.Responses.Escalate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EscalateStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EscalateStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualWorkFriendBot.Responses.Escalate.EscalateStrings", typeof(EscalateStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like us to share your information with the therapist before your first appointment?.
        /// </summary>
        public static string DATA_CONSENT {
            get {
                return ResourceManager.GetString("DATA_CONSENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am sorry, but I could not find any therapists matching your criteria..
        /// </summary>
        public static string NONE_FOUND {
            get {
                return ResourceManager.GetString("NONE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to talk to a human?.
        /// </summary>
        public static string PHONE_INFO {
            get {
                return ResourceManager.GetString("PHONE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like us to share your information with the therapist?.
        /// </summary>
        public static string THERAPIST_DATA_CONSENT {
            get {
                return ResourceManager.GetString("THERAPIST_DATA_CONSENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you prefer a therapist of your ethnicity?.
        /// </summary>
        public static string THERAPIST_ETHNICITY {
            get {
                return ResourceManager.GetString("THERAPIST_ETHNICITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string THERAPIST_GENDER {
            get {
                return ResourceManager.GetString("THERAPIST_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you prefer to meet your therapist in-person or virtually?.
        /// </summary>
        public static string THERAPIST_ONLINE {
            get {
                return ResourceManager.GetString("THERAPIST_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a radius for the search (in miles)..
        /// </summary>
        public static string THERAPIST_RADIUS {
            get {
                return ResourceManager.GetString("THERAPIST_RADIUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you! Give me a moment while I search for professionals based on your preferences..
        /// </summary>
        public static string THERAPIST_SEARCH {
            get {
                return ResourceManager.GetString("THERAPIST_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string THERAPIST_TOPIC {
            get {
                return ResourceManager.GetString("THERAPIST_TOPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What city would you like me to search for therapist recommendations?.
        /// </summary>
        public static string USER_LOCATION {
            get {
                return ResourceManager.GetString("USER_LOCATION", resourceCulture);
            }
        }
    }
}
